[ConsoleVariables]
# Copy this file into "Documents\My Games\FINAL FANTASY VII REBIRTH\Saved\Config\WindowsNoEditor\" folder, as Engine.ini
# and add any cvar changes you want the game to use inside this [ConsoleVariables] section.
# (you might need to create the WindowsNoEditor folder if it doesn't exist)
#
# After setting cvars here, you can check they've applied by opening dev-console ingame and entering the cvar name (without the =value)
# If they haven't taken affect, try renaming Engine.ini to Engine instead
# as some systems may be hiding the existing .ini extension (Windows hides extensions by default)
#
# (note: FFVIIHook patches game to make [ConsoleVariables] settings always take priority over other values for the cvar, so they won't be overridden by device profile INIs or other code)

# Uncomment lines below to disable the dynamic resolution used by the game
#r.DynamicRes.OperationMode=0
#r.DynamicRes.MinScreenPercentage=100

